version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - food-order-net
  food-order-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: food-order-kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://food-order-kafka:9092,PLAINTEXT_HOST://food-order-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - food-order-kafka-volume:/var/lib/kafka/data
    networks:
      - food-order-net
  food-order-order-mysql:
    image: mysql:8.0
    volumes:
      - food-order-order-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=FOOD_ORDER_CASE_ORDER
      - MYSQL_USER=FOOD_ORDER_CASE_ORDER_USER
      - MYSQL_PASSWORD=FOOD_ORDER_CASE_ORDER_USER
    ports:
      - 3307:3306
    networks:
      - food-order-net

  food-order-restaurant-mysql:
    image: mysql:8.0
    volumes:
      - food-order-restaurant-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=FOOD_ORDER_CASE_RESTAURANT
      - MYSQL_USER=FOOD_ORDER_CASE_RESTAURANT_USER
      - MYSQL_PASSWORD=FOOD_ORDER_CASE_RESTAURANT_USER
    ports:
      - 3308:3306
    networks:
      - food-order-net

  food-order-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - food-order-redis-volume:/data

  restaurant-api:
    image: restaurant-api-image:latest
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - DATASOURCE_URL=jdbc:mysql://food-order-restaurant-mysql:3306/FOOD_ORDER_CASE_RESTAURANT?useSSL=false&allowPublicKeyRetrieval=true
      - FLYWAY_DATASOURCE_URL=jdbc:mysql://food-order-restaurant-mysql:3306/mysql
    depends_on:
      - food-order-restaurant-mysql
    networks:
      - food-order-net

  order-api:
    image: order-api-image:latest
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      - DATASOURCE_URL=jdbc:mysql://food-order-order-mysql:3306/FOOD_ORDER_CASE_ORDER?useSSL=false&allowPublicKeyRetrieval=true
      - FLYWAY_DATASOURCE_URL=jdbc:mysql://food-order-order-mysql:3306/mysql
    depends_on:
      - food-order-kafka
      - food-order-order-mysql
      - food-order-redis
    networks:
      - food-order-net

volumes:
  food-order-restaurant-mysql-volume:
  food-order-order-mysql-volume:
  food-order-redis-volume:
  food-order-kafka-volume:
networks:
  food-order-net:
    driver: bridge