version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - craftgate-net
  craftgate-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: craftgate-kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://craftgate-kafka:9092,PLAINTEXT_HOST://craftgate-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - craftgate-kafka-volume:/var/lib/kafka/data
    networks:
      - craftgate-net
  craftgate-order-mysql:
    image: mysql:8.0
    volumes:
      - craftgate-order-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=CRAFT_GATE_ORDER
      - MYSQL_USER=CRAFT_GATE_ORDER_USER
      - MYSQL_PASSWORD=CRAFT_GATE_ORDER_USER
    ports:
      - 3307:3306
    networks:
      - craftgate-net

  craftgate-restaurant-mysql:
    image: mysql:8.0
    volumes:
      - craftgate-restaurant-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=CRAFT_GATE_RESTAURANT
      - MYSQL_USER=CRAFT_GATE_RESTAURANT_USER
      - MYSQL_PASSWORD=CRAFT_GATE_RESTAURANT_USER
    ports:
      - 3308:3306
    networks:
      - craftgate-net

  craftgate-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - craftgate-redis-volume:/data

  restaurant-api:
    image: restaurant-api-image:latest
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - DATASOURCE_URL=jdbc:mysql://craftgate-restaurant-mysql:3306/CRAFT_GATE_RESTAURANT?useSSL=false&allowPublicKeyRetrieval=true
      - FLYWAY_DATASOURCE_URL=jdbc:mysql://craftgate-restaurant-mysql:3306/mysql
    depends_on:
      - craftgate-restaurant-mysql
    networks:
      - craftgate-net

  order-api:
    image: order-api-image:latest
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      - DATASOURCE_URL=jdbc:mysql://craftgate-order-mysql:3306/CRAFT_GATE_ORDER?useSSL=false&allowPublicKeyRetrieval=true
      - FLYWAY_DATASOURCE_URL=jdbc:mysql://craftgate-order-mysql:3306/mysql
    depends_on:
      - craftgate-kafka
      - craftgate-order-mysql
      - craftgate-redis
    networks:
      - craftgate-net

volumes:
  craftgate-restaurant-mysql-volume:
  craftgate-order-mysql-volume:
  craftgate-redis-volume:
  craftgate-kafka-volume:
networks:
  craftgate-net:
    driver: bridge